import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { Avatar, Button } from "@mui/material";
import React from "react";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* <Image src="https://d1csarkz8obe9u.cloudfront.net/posterpreviews/business-logo-design-template-78655edda18bc1196ab28760f1535baa_screen.jpg?ts=1617645324" width={20} height={20}></Image> */}
            {/* <div className="d-flex">sdsds lknlknl</div>
            <Button variant="contained">Contained</Button>
            <Avatar sx={{ bgcolor: "orange" }}>H</Avatar> */}
            <div className="d-flex flex-column align-items-center p-5 gap-5">
                <span className="fs-3" style={{ color: "white" }}>
                    個人中心
                </span>
                <Avatar sx={{ bgcolor: "orange" }}>H</Avatar>
                <span style={{ color: "white" }}>92198360</span>
                <span className="fs-1" style={{ color: "red" }}>
                    餘額: 5,000,000
                </span>
                <div className="d-flex">
                    <Button className="mx-5 btn-lg" variant="contained" style={{ padding: "10px 40px" }}>
                        充值
                    </Button>
                    <Button className="mx-5 btn-lg" variant="contained" style={{ padding: "10px 40px" }}>
                        提現
                    </Button>
                </div>
            </div>
            <div className="d-flex justify-content-center" style={{ gap: "60px" }}>
                <div className="d-flex flex-column" style={{ width: 50 }}>
                    <Image src="http://www.clker.com/cliparts/1/1/Y/Z/2/O/blue-van-md.png" width={20} height={40}></Image>
                    <span style={{ color: "white" }}>基金寶</span>
                </div>
                <div className="d-flex flex-column" style={{ width: 50 }}>
                    <Image src="http://www.clker.com/cliparts/7/8/1/b/1194983790162955575sim_borja_bravo_01.svg.med.png" width={20} height={40}></Image>
                    <span style={{ color: "white" }}>平倉查詢</span>
                </div>
                <div className="d-flex flex-column" style={{ width: 50 }}>
                    <Image src="http://www.clker.com/cliparts/7/9/0/7/1217861777757435650mightyman_Button_Icons_6.svg.med.png" width={20} height={40}></Image>
                    <span style={{ color: "white" }}>收支明細</span>
                </div>
                <div className="d-flex flex-column" style={{ width: 50 }}>
                    <Image src="http://www.clker.com/cliparts/3/2/c/9/11949844881057808103megaphone_nicu_buculei_01.svg.med.png" width={20} height={40}></Image>
                    <span style={{ color: "white" }}>平台公告</span>
                </div>
            </div>
            {/* sdsd */}
            {/* <footer className={styles.footer}>
                <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer> */}
        </div>
    );
}
