import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { Avatar, Button } from "@mui/material";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Image src="https://d1csarkz8obe9u.cloudfront.net/posterpreviews/business-logo-design-template-78655edda18bc1196ab28760f1535baa_screen.jpg?ts=1617645324" width={20} height={20}></Image>
            <div className="d-flex">sdsds lknlknl</div>
            <Button variant="contained">Contained</Button>
            <Avatar sx={{ bgcolor: "orange" }}>H</Avatar>
            {/* <footer className={styles.footer}>
                <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer> */}
        </div>
    );
}
